### ISSUE TITLE
Possible Issues with FindPackageStandardArgs

### ISSUE THREAD

**Issue by DeveloperPaul123** [BlankSpruce/gersemi#1]
I gave this a try on a rather large project and I think I've found a small problem. Not sure if I'm misunderstanding what the format should look like, but I don't think the formatting of `find_package_standard_args` looks correct. Example output:

```cmake
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    Pylon
    REQUIRED_VARS
    PYLON_INCLUDE_DIR
    PYLON_BASE_LIBRARY
    PYLON_GC_BASE_LIBRARY
    PYLON_GENAPI_LIBRARY
    PYLON_UTILITY_LIBRARY
    # omitted for brevity
    FOUND_VAR
    PYLON_FOUND
    VERSION_VAR
    PYLON_VERSION
    FAIL_MESSAGE
    "Failed to find Pylon"
)
```

I would think something like this "should" be the output:

```cmake
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    Pylon
    REQUIRED_VARS
        PYLON_INCLUDE_DIR
        PYLON_BASE_LIBRARY
        PYLON_GC_BASE_LIBRARY
        PYLON_GENAPI_LIBRARY
        PYLON_UTILITY_LIBRARY
    # omitted for brevity
    FOUND_VAR PYLON_FOUND
    VERSION_VAR PYLON_VERSION
    FAIL_MESSAGE "Failed to find Pylon"
)
```

Is this an actual issue? Or do I need to point `gersemi` to the modules directory for my CMake installation (`FindPackageStandardArgs` is included with CMake).

**Comment by BlankSpruce** [comment]
Your understading for the style is correct however I'm not able to reproduce your case. Are you sure you haven't reduced the example too much? I suspect there might be some interaction with comments hence please double check your example.

> Is this an actual issue? Or do I need to point gersemi to the modules directory for my CMake installation (FindPackageStandardArgs is included with CMake).

It sounds like an issue. Also cmake native modules aren't required to be pointed nor it would be useful in many cases.

**Comment by BlankSpruce** [comment]
I had a couple of minutes and I think I've found possible case you might have stumbled upon. For the record:

Input:
```cmake
find_package_handle_standard_args(
    Pylon FOUND_VAR PYLON_FOUND
    # foobar
    REQUIRED_VARS PYLON_INCLUDE_DIR PYLON_BASE_LIBRARY PYLON_GC_BASE_LIBRARY PYLON_GENAPI_LIBRARY PYLON_UTILITY_LIBRARY
)
```
Output:
```cmake
find_package_handle_standard_args(
    Pylon
    FOUND_VAR PYLON_FOUND
    # foobar
    REQUIRED_VARS
    PYLON_INCLUDE_DIR
    PYLON_BASE_LIBRARY
    PYLON_GC_BASE_LIBRARY
    PYLON_GENAPI_LIBRARY
    PYLON_UTILITY_LIBRARY
)
```
Expected:
```cmake
find_package_handle_standard_args(
    Pylon
    FOUND_VAR PYLON_FOUND
    # foobar
    REQUIRED_VARS
        PYLON_INCLUDE_DIR
        PYLON_BASE_LIBRARY
        PYLON_GC_BASE_LIBRARY
        PYLON_GENAPI_LIBRARY
        PYLON_UTILITY_LIBRARY
)
```

Definitely a bug.

**Comment by DeveloperPaul123** [comment]
Thanks for fixing this; will it be pushed to a new release soon?

**Comment by BlankSpruce** [comment]
Late response: it's already there in 0.4.0 release.
