### ISSUE TITLE
Forced line break → AST mismatch after formatting

### ISSUE THREAD

**Issue by anordal** [BlankSpruce/gersemi#16]
In this example, the command line was long, so I tried to break it up using forced line breaks (empty line comments) …

```CMake
set(SRC
    src/file.c
)

add_custom_command(
    OUTPUT
        src.tar.zst
    DEPENDS
        ${SRC}
    COMMAND
        set -euo pipefail #
        && tar -c src | zstd --ultra -22 > src.tar.zst #
)
```

… but Gersemi 0.11.0 didn't like that:

> CMakeLists.txt: AST mismatch after formatting

**Comment by BlankSpruce** [comment]
Fixed in 0.11.1.

Quite clever usage of line comment to break COMMAND argument.
