### ISSUE TITLE
Nondeterministic formatting of lists containing keywords

### ISSUE THREAD

**Issue by anordal** [BlankSpruce/gersemi#32]
With Gersemi 0.13.5 (specifically commit 141df8c74), when configured to `favour-expansion`, lists containing common keywords are sometimes formatted vertically as before, but sometimes horizontally.

Can be reproduced (with a few tries) by running `gersemi --diff --color .` in a directory containing these 3 files:

.gersemirc

    list_expansion: favour-expansion

unrelated.cmake

    target_link_libraries(unrelated PRIVATE pthread)

list_containing_keyword.cmake

```
set(list_containing_keyword
    PUBLIC
    pthread
)
```

**Comment by BlankSpruce** [comment]
Long time no see. Thanks for narrowing down the regression. 0.13.6 with the fix will be available soon.
