### ISSUE TITLE
Underscored built-in function not recognized

### ISSUE THREAD

**Issue by omartijn** [BlankSpruce/gersemi#41]
CMakeLists.txt:

```
function(install)
    _install(${ARGV})
endfunction()
```

yields:

```
Warning: unknown command '_install' used at:
/pathCMakeLists.txt:4:5
```

**Comment by BlankSpruce** [comment]
Can you point me CMake doc that says `__install` is available for users? I've based builtins on [this page](https://cmake.org/cmake/help/latest/manual/cmake-commands.7.html) and [these pages](https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html).

**Comment by omartijn** [comment]
I cannot find any concrete documentation on it (because it was never intended to be used as a feature by users), but if you define a function in CMake _and the function already exists_, the original function is now available under the same name, prefixed with a single underscore.

This means that if I define `function(install)`, then the original function is available as `_install`, and thus gersemi should know that it exists and what features it supports.

**Comment by BlankSpruce** [comment]
Wow, I'll look more into this, I've never known about that feature.

**Comment by BlankSpruce** [comment]
On one hand it seems this feature was implemented back in 2005 so there was plenty of time for Hyrum's law to claim its victims: 
https://gitlab.kitware.com/cmake/cmake/-/commit/24a5c0a72e5a50637a285c1dd5427a6bb498ca06
It evolved to its current form here: 
https://gitlab.kitware.com/cmake/cmake/-/blame/v3.31.0-rc3/Source/cmState.cxx?ref_type=tags#L523

On the other hand it seems that CMake maintainers intentionally avoid making this feature officially available in such direct form:
https://gitlab.kitware.com/cmake/cmake/-/issues/23482#note_1183273
https://gitlab.kitware.com/cmake/cmake/-/issues/23482#note_1183174
https://crascit.com/2018/09/14/do-not-redefine-cmake-commands/
In chapter 8.6 "Recommended practices" of [1st edition of referred book](https://crascit.com/professional-cmake/) there is this recommendation:
> Do not define or call a function or macro with a name that starts with a single underscore. In
particular, do not rely on the undocumented behavior whereby the old implementation of a
command is made available by such a name when a function or macro redefines an existing
command.

Given these circumstances I don't intend to support that feature.

**Comment by omartijn** [comment]
It's a feature (ab)used by many, including https://github.com/microsoft/vcpkg
It'd be really really nice if this could be implemented.
