### ISSUE TITLE
Excluding subdirectories from `definitions`

### ISSUE THREAD

**Issue by ManifoldFR** [BlankSpruce/gersemi#44]
Hi, thank you for this great project of providing a new, maintained CMake formatter for the open-source community. Our orgs have already switched from cmake-format to gersemi and it's been really great (less warnings, no more inconsistent results between linting and formatting!) so far.

I have a question/request about where we grab our function and macro definitions for the linter/formatter:

The use case is as follows:
- we define a bunch of functions/macros in the CMake project's root dir `./`
- this pulls in all subdirectories recursively, including our CMake build dir
- we have another cmake project pulled in by `FetchContent`, which gets checked out under our build directory
- the `FetchContent`'d project also defines functions/macros with the same names as ours (probably due to shared CMake module code, etc) which can have different definitions, we get a flurry of warnings.

I think it'd be a good option to be able to exclude stuff from the `definitions` config option. Maybe by looking at the .gitignore file?

**Comment by BlankSpruce** [comment]
My current stance on supporting `.gitignore` and any such file [is presented here](https://github.com/BlankSpruce/gersemi/issues/42#issuecomment-2477128220). That stance of course is related to target files and how to select them while you're problem is strictly related to `definitions` so the reasoning for that case might not be completely suitable.

I don't want to provide poor answer to your problem due incomplete understanding so I'd like to ask for the following clarifications:
1. By "we get a flurry of warnings" I presume you refer to "conflicting definitions" warning, is that right?
2. I presume we are interested in proper formatting of files only within the project scope while not touching the files coming from elsewhere (git submodules, `FetchContent`, etc.), correct?
3. Is [`# gersemi: ignore`](https://github.com/BlankSpruce/gersemi?tab=readme-ov-file#gersemi-ignore) too weak or improperly targetted for the essence of the issue?
4. Could you provide a link to exact project where the issue happens with short instruction (if not already available in project's readme) how to setup your use case? I'd like to experiment with the project to better understand the pain points, to feel why it's annoying/inconvenient, to understand whether it's possible to mitigate that issue with current capabilities of gersemi, etc.

**Comment by ClausKlein** [comment]
see too https://github.com/BlankSpruce/gersemi/issues/45

**Comment by BlankSpruce** [comment]
@ManifoldFR 
Could you provide answers to my previous message? I'd like to address your issue the best way possible. Of course I can wait if you are too busy with other stuff taking your attention.

**Comment by ManifoldFR** [comment]
Hello @BlankSpruce, sorry it took so much time getting back to you, other things had come up.

1. The warnings indeed are about conflicting definitions.
2. It is only about the formatting about files in our project outside of submodules and CMake fetches, but we've had no issues at all on this point. We just let a pre-commit call handle formatting our desired files for us.
3. I don't think `#gersemi ignore` helps us here? Maybe I am misunderstanding?
4. Our project is here: https://github.com/Simple-Robotics/aligator/tree/devel.
It comes with a submodule called `cmake` (pointing [here](https://github.com/jrl-umi3218/jrl-cmakemodules)) which is a common set of CMake modules used across our orgs. If one sets the CMake option `GENERATE_PYTHON_STUBS` to true, then a project called [`pybind11-stubgen`](https://github.com/jcarpent/pybind11-stubgen) is fetched -- and it also has the same submodule (not necessarily the latest commit), hence conflicting definitions would arise.

So far, my solution has been to only add specific directories and files to `definitions` (instead of just `definitions = [./]`) so as to avoid including my build directory. It has worked well enough.

**Comment by BlankSpruce** [comment]
In general I'd recommend narrowing down `definitions` to specific directories that might contain custom command definitions rather than whole project because searching and interpreting these definitions doesn't come for free. Having said that you have very interesting use-case where I think you'd be highly interested in taking those external definitions into account.

I'll experiment some more with the project but overall it seems that such `.gersemirc` would be okay although it requires that submodule is initialized and up to date:
```yaml
definitions: [./CMakeLists.txt, ./examples, ./tests, ./bindings, ./cmake]
line_length: 80
indent: 2
warn_about_unknown_commands: false
```

Pre-commit hook managed to apply formatting to some more commands (I've added fake `FROMBULATE____` language to your `compute_project_args`). In particular you can see that gersemi used canonical spelling from these definitions, examples:
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/29c0eb4e659304f44d55a0389e2749812d858659/base.cmake#L379
https://github.com/jrl-umi3218/jrl-cmakemodules/blob/29c0eb4e659304f44d55a0389e2749812d858659/package-config.cmake#L74
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index accbc6d3..0b4be91d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -76,7 +76,12 @@ if(POLICY CMP0167)
   set(CMAKE_POLICY_DEFAULT_CMP0167 NEW)
 endif()
 include(${JRL_CMAKE_MODULES}/base.cmake)
-compute_project_args(PROJECT_ARGS LANGUAGES CXX)
+COMPUTE_PROJECT_ARGS(
+  PROJECT_ARGS
+  LANGUAGES
+    CXX
+    FROMBULATE____________________________________________________________________________
+)
 project(${PROJECT_NAME} ${PROJECT_ARGS})
 set(CMAKE_VERBOSE_MAKEFILE OFF)
 
@@ -104,7 +109,7 @@ elseif(UNIX)
 endif()
 include(CMakeDependentOption)
 
-apply_default_apple_configuration()
+APPLY_DEFAULT_APPLE_CONFIGURATION()
 
 if(WIN32)
   set(LINK copy_if_different)
@@ -204,19 +209,34 @@ endif()
 # ----------------------------------------------------
 # --- DEPENDENCIES -----------------------------------
 # ----------------------------------------------------
-add_project_dependency(Eigen3 3.3.7 REQUIRED PKG_CONFIG_REQUIRES "eigen3 >= 3.3.7")
-add_project_dependency(fmt "10.0.0...<12" REQUIRED PKG_CONFIG_REQUIRES "fmt >= 10.0.0")
+ADD_PROJECT_DEPENDENCY(
+  Eigen3
+  3.3.7
+  REQUIRED
+  PKG_CONFIG_REQUIRES "eigen3 >= 3.3.7"
+)
+ADD_PROJECT_DEPENDENCY(
+  fmt
+  "10.0.0...<12"
+  REQUIRED
+  PKG_CONFIG_REQUIRES "fmt >= 10.0.0"
+)
 
 if(BUILD_WITH_OPENMP_SUPPORT)
-  add_project_dependency(OpenMP REQUIRED)
+  ADD_PROJECT_DEPENDENCY(OpenMP REQUIRED)
   add_compile_definitions(ALIGATOR_MULTITHREADING)
 endif()
 
 set(BOOST_REQUIRED_COMPONENTS filesystem)
-set_boost_default_options()
-export_boost_default_options()
-add_project_dependency(Boost REQUIRED COMPONENTS ${BOOST_REQUIRED_COMPONENTS})
-add_project_dependency(proxsuite-nlp 0.10.0 REQUIRED PKG_CONFIG_REQUIRES "proxsuite-nlp >= 0.10.0")
+SET_BOOST_DEFAULT_OPTIONS()
+EXPORT_BOOST_DEFAULT_OPTIONS()
+ADD_PROJECT_DEPENDENCY(Boost REQUIRED COMPONENTS ${BOOST_REQUIRED_COMPONENTS})
+ADD_PROJECT_DEPENDENCY(
+  proxsuite-nlp
+  0.10.0
+  REQUIRED
+  PKG_CONFIG_REQUIRES "proxsuite-nlp >= 0.10.0"
+)
 
 if(BUILD_WITH_PINOCCHIO_SUPPORT)
   message(STATUS "Building aligator with Pinocchio support.")
@@ -253,7 +273,7 @@ if(BUILD_WITH_CHOLMOD_SUPPORT)
     ${JRL_CMAKE_MODULES}/find-external/CHOLMOD
     ${CMAKE_MODULE_PATH}
   )
-  add_project_dependency(CHOLMOD REQUIRED)
+  ADD_PROJECT_DEPENDENCY(CHOLMOD REQUIRED)
   message(
     STATUS
     "Build with CHOLMOD support (LGPL). See CHOLMOD/Doc/License.txt for further details."
@@ -263,7 +283,12 @@ endif()
 
 if(BUILD_PYTHON_INTERFACE)
   set(PYTHON_COMPONENTS Interpreter Development NumPy)
-  add_project_dependency(eigenpy 3.7.0 REQUIRED PKG_CONFIG_REQUIRES "eigenpy >= 3.7.0")
+  ADD_PROJECT_DEPENDENCY(
+    eigenpy
+    3.7.0
+    REQUIRED
+    PKG_CONFIG_REQUIRES "eigenpy >= 3.7.0"
+  )
   set(PYLIB_NAME "py${PROJECT_NAME}")
   set(${PYLIB_NAME}_INSTALL_DIR ${PYTHON_SITELIB}/${PROJECT_NAME})
 endif()
@@ -338,7 +363,7 @@ if(ALIGATOR_TRACY_ENABLE AND DOWNLOAD_TRACY)
   endif()
 elseif(ALIGATOR_TRACY_ENABLE)
   # assume it is installed somewhere
-  add_project_dependency(Tracy)
+  ADD_PROJECT_DEPENDENCY(Tracy)
   set_target_properties(
     Tracy::TracyClient
     PROPERTIES POSITION_INDEPENDENT_CODE True
@@ -415,8 +440,8 @@ endfunction()
 
 create_library()
 
-add_header_group(LIB_HEADERS)
-add_source_group(LIB_SOURCES)
+ADD_HEADER_GROUP(LIB_HEADERS)
+ADD_SOURCE_GROUP(LIB_SOURCES)
 
 install(
   TARGETS ${PROJECT_NAME}
@@ -439,7 +464,7 @@ if(DOWNLOAD_TRACY)
 endif()
 
 if(BUILD_CROCODDYL_COMPAT)
-  add_project_dependency(crocoddyl REQUIRED)
+  ADD_PROJECT_DEPENDENCY(crocoddyl REQUIRED)
   add_subdirectory(src/compat/crocoddyl)
 endif()
 
@@ -463,7 +488,7 @@ macro(create_ex_or_bench is_bench exfile exname)
 endmacro()
 
 if(BUILD_WITH_PINOCCHIO_SUPPORT AND (BUILD_EXAMPLES OR BUILD_BENCHMARKS))
-  add_project_private_dependency(example-robot-data 4.0.9 REQUIRED)
+  ADD_PROJECT_PRIVATE_DEPENDENCY(example-robot-data 4.0.9 REQUIRED)
   macro(target_add_example_robot_data target_name)
     target_link_libraries(
       ${target_name}
@@ -560,14 +585,14 @@ if(BUILD_WITH_OPENMP_SUPPORT)
 endif()
 if(BUILD_CROCODDYL_COMPAT)
   EXPORT_VARIABLE(ALIGATOR_WITH_CROCODDYL_COMPAT ON)
-  pkg_config_append_libs(aligator_croc_compat)
+  PKG_CONFIG_APPEND_LIBS(aligator_croc_compat)
 endif()
 
-pkg_config_append_libs(${PROJECT_NAME})
-pkg_config_append_boost_libs(${BOOST_REQUIRED_COMPONENTS})
-pkg_config_append_cflags("${CFLAGS_DEPENDENCIES}")
+PKG_CONFIG_APPEND_LIBS(${PROJECT_NAME})
+PKG_CONFIG_APPEND_BOOST_LIBS(${BOOST_REQUIRED_COMPONENTS})
+PKG_CONFIG_APPEND_CFLAGS("${CFLAGS_DEPENDENCIES}")
 
 # Install catkin package.xml
 install(FILES package.xml DESTINATION share/${PROJECT_NAME})
 
-setup_project_finalize()
+SETUP_PROJECT_FINALIZE()
```

I'll try to think about something to make this usage pattern easier to apply without a gotcha "you forgot to initialize submodule". As of now if you:
1. run formatter with uninitialized submodule
2. run pre-commit hook
3. then initialize that submodule
4. run pre-commit hook

gersemi won't reformat the files due to caching which is unintended behaviour in such case.

**Comment by ManifoldFR** [comment]
Thanks a lot for this investigation !

I've decided to add our submodule to the gersemi `definitions` config. Building the project straight up does not work unless the submodule is checked out or fetched (our CMake listfile performs a fetch as a fallback when the submodule isn't found), but we'll keep in mind whenever we have the situation you mentioned (attempting to format before the `cmake/` dir is present). We'll also keep in mind your advice on explicitly listing where we want definitions from.

**Comment by ManifoldFR** [comment]
For completeness: [here](https://pre-commit.ci/#configuration-submodules) is the pre-commit CI config option to ask it to checkout submodules when it checks project for linting.
