### ISSUE TITLE
No custom formatter for `exec_program()`

### ISSUE THREAD

**Issue by adriaandegroot** [BlankSpruce/gersemi#7]
There is no custom formatter for `exec_program()`, so the arguments are not indented at all.

For instance, this input remains unchanged:

```
macro(GET_PROJECT_GIT_VERSION)
    find_package(Git QUIET)
    if(Git_FOUND)
        message(STATUS "Looking for git-versioning information.")
        exec_program(
            ${GIT_EXECUTABLE}
            ${CMAKE_CURRENT_SOURCE_DIR}
            ARGS
            describe
            --tags
            --match
            'v[0-9]*.*.*'
            --dirty
            OUTPUT_VARIABLE
            GIT_VERSION_INFO
            RETURN_VALUE
            GIT_ERROR
        )
    endif()
endmacro()
```

I would expect *ARGS* to be indented (muti-value option) and *OUTPUT_VARIABLE* and *RETURN_VALUE* to pull their single argument onto their own line.

**Comment by adriaandegroot** [comment]
The `exec_program()` command has been deprecated since CMake 3.0 and is superceded by `execute_process()` which **is** correctly formatted. It's actually a good thing gersemi doesn't format it, it's a sign it should be replaced in the CMake code that is being formatted.

> I'm filing this issue so that it can be closed as "not supporting deprecated methods" -- just in case people complain about it. Since there's a lot of `_uninstall.cmake` examples floating around that use `exec_program()`, it might come up occasionally.

**Comment by BlankSpruce** [comment]
With your finding it occurred to me now that I haven't specified anywhere that only CMake 3 is supported. I'll improve README about that since it's kind of significant detail. Thanks for letting me know.

**Comment by BlankSpruce** [comment]
Here it is: 69bacb2
